mysql:
  username: root
  password: 12345678
  schema: snackhub-menu
  #url: snackhub-menu-mysql-db
  #port: 3306
  url: 127.0.0.1
  port: 3307

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

